# Log configuration for Synapse
version: 1

formatters:
    precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

handlers:
    file:
        class: logging.handlers.TimedRotatingFileHandler
        formatter: precise
        filename: /data/logs/homeserver.log
        when: midnight
        backupCount: 3
        encoding: utf8

    # Log to stdout for Docker container logs
    console:
        class: logging.StreamHandler
        formatter: precise
        stream: ext://sys.stdout

loggers:
    synapse.storage.SQL:
        level: WARN

    synapse.access.http.8008:
        level: WARN

root:
    level: INFO
    handlers: [file, console]

disable_existing_loggers: false